# Generated by Django 4.1.7 on 2023-04-02 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("to_do_manager", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="deadline",
            field=models.DateField(blank=True, null=True),
        ),
    ]
